version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://mod-search:8081
    depends_on:
      - backend

  backend:
    build: ./mod-search  # This should contain Dockerfile for your Spring Boot app
    ports:
      - "8082:8081"    # Spring Boot default port
    environment:
      - REDIS_URL=redis://redis:6379
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_MASTER_KEY=masterKey
    depends_on:
      - redis
      - meilisearch

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
